stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .

deploy:
  stage: deploy
  services:
    - name: docker:dind
  script:
    - sleep 10  # App ko time dena
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm -d -p 5000:5000 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - curl -f http://localhost:5000 || exit 1
