stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/flask-app

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_REF_NAME

test:
  stage: test
  script:
    - docker run --rm -d -p 5000:5000 $DOCKER_IMAGE:$CI_COMMIT_REF_NAME
    - curl -f http://localhost:5000 || exit 1

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Deployment commands or scripts go here
