stages:
  - build
  - test
  - deploy

# Build stage
build:
  stage: build
  script:
    - docker build -t myapp .

# Test stage
test:
  stage: test
  script:
    - docker run -d -p 5000:5000 myapp
    - curl http://localhost:5000

# Deploy stage
deploy:
  stage: deploy
  script:
    - docker push myapp:latest
