image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache curl  # Installs curl in Alpine-based images
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

test:
  stage: test
  script:
    - docker run --rm -d -p 5000:5000 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - curl -f http://localhost:5000 || exit 1  # Test with curl

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
